<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.guard.main' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\Authentication\\Provider\\AuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-guard\\Provider\\GuardAuthenticationProvider.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\UserCheckerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\UserChecker.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\UserProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\security-core\\User\\InMemoryUserProvider.php';

return $this->privates['security.authentication.provider.guard.main'] = new \Symfony\Component\Security\Guard\Provider\GuardAuthenticationProvider(new RewindableGenerator(function () {
    yield 0 => ($this->privates['App\Security\AppAuthenticationAuthenticator'] ?? ($this->privates['App\Security\AppAuthenticationAuthenticator'] = new \App\Security\AppAuthenticationAuthenticator()));
}, 1), ($this->privates['security.user.provider.concrete.in_memory'] ?? ($this->privates['security.user.provider.concrete.in_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([]))), 'main', new \Symfony\Component\Security\Core\User\UserChecker());
