<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKm7rbbB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKm7rbbB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKm7rbbB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKm7rbbB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKm7rbbB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Km7rbbB',
    'container.build_id' => 'b27950c7',
    'container.build_time' => 1550499124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKm7rbbB');
