<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7XWhmKu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7XWhmKu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7XWhmKu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7XWhmKu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7XWhmKu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7XWhmKu',
    'container.build_id' => '736f63af',
    'container.build_time' => 1552314328,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7XWhmKu');
